-- 001_init.sql — tabele bazowe w schemacie `app`.
--
-- Schematy `app` i `reporting` JUZ ISTNIEJA na serwerze docelowym i naleza do
-- roli poleasingowe_app (SPEC.md §0). Migracja ich nie tworzy — zaczyna od
-- tabel. Pilnuje tego test poleasingowe/tests/unit/test_migracje.py.
--
-- Bez rozszerzen (SPEC.md §8.3). Statusy jako text + CHECK, nie enum
-- PostgreSQL, bo ich migracje bola (§8.2). Kwoty jako numeric(12,2) plus
-- kolumna waluty — nigdy float. Czas jako timestamptz, wszystko w UTC.

-- Rejestr zastosowanych migracji (SPEC.md §5).
CREATE TABLE IF NOT EXISTS app.schema_migration (
    version     integer     PRIMARY KEY,
    name        text        NOT NULL,
    applied_at  timestamptz NOT NULL DEFAULT now(),
    checksum    text        NOT NULL
);

COMMENT ON TABLE app.schema_migration IS
    'Ktora migracja zostala zastosowana. checksum wykrywa edycje pliku po fakcie.';


CREATE TABLE IF NOT EXISTS app.source (
    id                          integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key                         text        NOT NULL UNIQUE,
    name                        text        NOT NULL,
    enabled                     boolean     NOT NULL DEFAULT true,
    sweep_interval_seconds      integer     NOT NULL DEFAULT 21600,
    rate_limit_per_minute       integer     NOT NULL DEFAULT 30,
    floor_seconds               integer     NOT NULL DEFAULT 60,
    auth_state                  text        NOT NULL DEFAULT 'ANONYMOUS',
    consecutive_auth_failures   integer     NOT NULL DEFAULT 0,

    -- Parametry dogrywki (SPEC.md §11.2, §11.5). Kolumny, nie stale w kodzie:
    -- cztery zbadane serwisy maja cztery rozne reguly, a jeden nie ma
    -- dogrywki wcale (RECON.md §3.2). Zera oznaczaja serwis bez dogrywki.
    overtime_window_seconds     integer     NOT NULL DEFAULT 0,
    overtime_extension_seconds  integer     NOT NULL DEFAULT 0,
    overtime_cap_seconds        integer,

    CONSTRAINT source_auth_state_check
        CHECK (auth_state IN ('ANONYMOUS', 'OK', 'EXPIRED', 'LOCKED')),
    CONSTRAINT source_floor_dodatni
        CHECK (floor_seconds > 0),
    CONSTRAINT source_rate_limit_dodatni
        CHECK (rate_limit_per_minute > 0),
    CONSTRAINT source_dogrywka_spojna
        CHECK (
            (overtime_window_seconds = 0 AND overtime_extension_seconds = 0)
            OR (overtime_window_seconds > 0 AND overtime_extension_seconds > 0)
        ),
    CONSTRAINT source_licznik_logowan_nieujemny
        CHECK (consecutive_auth_failures >= 0)
);

COMMENT ON COLUMN app.source.floor_seconds IS
    'Dolna granica interwalu w endgame. Wyliczana z reguly: polowa okna '
    'dogrywki, nie mniej niz 10 s (SPEC.md §11.2). Wolno podniesc per zrodlo.';
COMMENT ON COLUMN app.source.overtime_cap_seconds IS
    'Sufit lacznego przedluzenia. NULL = serwis go nie deklaruje; wtedy '
    'faza czujki z §11.5 uzywa twardego limitu 30 minut.';


CREATE TABLE IF NOT EXISTS app.auction (
    id                      bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id               integer     NOT NULL REFERENCES app.source (id),
    external_id             text        NOT NULL,
    url                     text        NOT NULL,

    make                    text,
    model                   text,
    variant                 text,
    year                    integer,
    mileage_km              integer,
    fuel                    text,
    gearbox                 text,
    engine_ccm              integer,
    engine_hp               integer,
    vin                     text,
    body                    text,
    color                   text,
    location                text,
    seller                  text,

    price_start             numeric(12,2),
    price_current           numeric(12,2),
    currency                text        NOT NULL DEFAULT 'PLN',
    bid_count               integer,
    bid_increment_raw       text,

    ends_at                 timestamptz,
    status                  text        NOT NULL DEFAULT 'ACTIVE',
    first_seen_at           timestamptz NOT NULL DEFAULT now(),
    last_seen_at            timestamptz NOT NULL DEFAULT now(),

    content_hash            text,
    raw_json                jsonb,
    next_poll_at            timestamptz,
    poll_tier               text        NOT NULL DEFAULT 'IDLE',
    consecutive_failures    integer     NOT NULL DEFAULT 0,
    final_price_state       text        NOT NULL DEFAULT 'UNKNOWN',
    last_price_lead_seconds integer,
    duplicate_of            bigint      REFERENCES app.auction (id),

    CONSTRAINT auction_source_external_unique
        UNIQUE (source_id, external_id),
    CONSTRAINT auction_status_check
        CHECK (status IN ('ACTIVE', 'ENDING', 'ENDED', 'DISAPPEARED')),
    CONSTRAINT auction_final_price_state_check
        CHECK (final_price_state IN ('UNKNOWN', 'CONFIRMED', 'LAST_SEEN')),
    CONSTRAINT auction_poll_tier_check
        CHECK (poll_tier IN ('IDLE', 'FAR', 'NEAR', 'ENDGAME', 'CLOSING')),
    CONSTRAINT auction_currency_check
        CHECK (currency IN ('PLN', 'EUR')),
    -- SPEC.md §8.2: last_price_lead_seconds jest NULL dla CONFIRMED, bo tam
    -- pomiar jest z definicji dokladny. NULL jest tu znaczacy, nie przypadkowy.
    CONSTRAINT auction_lead_tylko_dla_last_seen
        CHECK (final_price_state <> 'CONFIRMED' OR last_price_lead_seconds IS NULL),
    CONSTRAINT auction_bid_count_nieujemny
        CHECK (bid_count IS NULL OR bid_count >= 0),
    CONSTRAINT auction_ceny_nieujemne
        CHECK (
            (price_start IS NULL OR price_start >= 0)
            AND (price_current IS NULL OR price_current >= 0)
        ),
    CONSTRAINT auction_nie_jest_duplikatem_siebie
        CHECK (duplicate_of IS NULL OR duplicate_of <> id)
);

COMMENT ON COLUMN app.auction.bid_increment_raw IS
    'Minimalne postapienie w postaci, w jakiej podal je serwis. Pole '
    'INFORMACYJNE, bez logiki domenowej (SPEC.md §8.2): EFL ma progi kwotowe, '
    'poleasingowe podaje instep_price, autoprzetarg liczy 2% ostatniej oferty.';
COMMENT ON COLUMN app.auction.raw_json IS
    'Trzymany tylko dla aukcji obserwowanych i zakonczonych (SPEC.md §8.4). '
    'Dla reszty NULL. Nie moze zawierac danych osobowych osob trzecich (§10.2).';
COMMENT ON COLUMN app.auction.duplicate_of IS
    'Deduplikacja miedzy serwisami po VIN — oznaczamy, nie usuwamy (§8.4).';


CREATE TABLE IF NOT EXISTS app.price_snapshot (
    id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id  bigint      NOT NULL REFERENCES app.auction (id) ON DELETE CASCADE,
    ts          timestamptz NOT NULL DEFAULT now(),
    price       numeric(12,2) NOT NULL,
    currency    text        NOT NULL DEFAULT 'PLN',
    bid_count   integer,
    ends_at     timestamptz,
    bid_gap     integer,

    CONSTRAINT price_snapshot_currency_check
        CHECK (currency IN ('PLN', 'EUR')),
    CONSTRAINT price_snapshot_cena_nieujemna
        CHECK (price >= 0),
    CONSTRAINT price_snapshot_bid_gap_nieujemny
        CHECK (bid_gap IS NULL OR bid_gap >= 0)
);

COMMENT ON TABLE app.price_snapshot IS
    'Zapisywany WYLACZNIE gdy zmienila sie cena, liczba ofert albo ends_at '
    '(SPEC.md §8.4). Odpyt bez zmiany aktualizuje tylko auction.last_seen_at.';
COMMENT ON COLUMN app.price_snapshot.bid_gap IS
    'Ile ofert przegapiono przed tym snapshotem (SPEC.md §11.8). Liczony '
    'wzgledem POPRZEDNIEGO snapshotu tej aukcji. NULL dla pierwszego '
    'snapshotu: aukcja mogla juz miec oferty, wiec 0 byloby klamstwem.';


CREATE TABLE IF NOT EXISTS app.watchlist (
    id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id   bigint      NOT NULL REFERENCES app.auction (id) ON DELETE CASCADE,
    note         text,
    target_price numeric(12,2),
    currency     text        NOT NULL DEFAULT 'PLN',
    added_at     timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT watchlist_currency_check
        CHECK (currency IN ('PLN', 'EUR')),
    CONSTRAINT watchlist_cena_nieujemna
        CHECK (target_price IS NULL OR target_price >= 0)
);


CREATE TABLE IF NOT EXISTS app.saved_filter (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text        NOT NULL UNIQUE,
    criteria   jsonb       NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);


CREATE TABLE IF NOT EXISTS app.run_log (
    id             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id      integer     NOT NULL REFERENCES app.source (id),
    started_at     timestamptz NOT NULL DEFAULT now(),
    finished_at    timestamptz,
    new_count      integer     NOT NULL DEFAULT 0,
    changed_count  integer     NOT NULL DEFAULT 0,
    error_count    integer     NOT NULL DEFAULT 0,
    errors         jsonb       NOT NULL DEFAULT '[]'::jsonb,
    rss_bytes      bigint,
    database_bytes bigint,
    notes          text,

    CONSTRAINT run_log_liczniki_nieujemne
        CHECK (new_count >= 0 AND changed_count >= 0 AND error_count >= 0)
);

COMMENT ON TABLE app.run_log IS
    'Po kazdym przebiegu RSS, rozmiar bazy i stan puli — budzet z SPEC.md §1.1 '
    'ma byc mierzalny, nie deklaratywny (§13).';


-- Indeksy (SPEC.md §8.3).
-- Czesciowy indeks na next_poll_at jest kluczowy: to zapytanie wykonuje sie
-- najczesciej i musi trafiac wylacznie w aktywne aukcje.
CREATE INDEX IF NOT EXISTS auction_next_poll_active_idx
    ON app.auction (next_poll_at) WHERE status = 'ACTIVE';
CREATE INDEX IF NOT EXISTS auction_status_ends_at_idx
    ON app.auction (status, ends_at);
CREATE INDEX IF NOT EXISTS auction_make_model_year_idx
    ON app.auction (make, model, year);
CREATE INDEX IF NOT EXISTS auction_vin_idx
    ON app.auction (vin) WHERE vin IS NOT NULL;
CREATE INDEX IF NOT EXISTS price_snapshot_auction_ts_idx
    ON app.price_snapshot (auction_id, ts DESC);
CREATE UNIQUE INDEX IF NOT EXISTS watchlist_auction_unique_idx
    ON app.watchlist (auction_id);
CREATE INDEX IF NOT EXISTS run_log_source_started_idx
    ON app.run_log (source_id, started_at DESC);
